# Generated by Django 4.0 on 2023-12-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.CharField(default=1983, max_length=250),
            preserve_default=False,
        ),
    ]
