# Generated by Django 4.0 on 2023-12-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='full_name',
            field=models.CharField(default=1993, max_length=250),
            preserve_default=False,
        ),
    ]
