# Generated by Django 4.0 on 2023-12-19 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_driver_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.FloatField(default=1983),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.FloatField(default=2023),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DriverRefuse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.driver')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.order')),
            ],
        ),
    ]
