# Generated by Django 4.0 on 2023-12-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_order_latitude_order_longitude_driverrefuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='latitude',
            field=models.FloatField(default=2023),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='longitude',
            field=models.FloatField(default=2023),
            preserve_default=False,
        ),
    ]
